services:
  ocserv:
    build: .
    container_name: ocserv
    privileged: true
    ports:
      - "8443:8443/tcp" # <-- 宿主机和容器内部端口保持一致
      - "8443:8443/udp" # <-- 宿主机和容器内部端口保持一致
    volumes:
      - ./config:/etc/ocserv
    environment:
      - VPN_PORT=8443 # <-- 【新增】通知 ocserv.conf 内部修改监听端口
      - VPN_USER=myvpnuser
      - VPN_PASSWORD=mypassword123
    restart: always
